import { motion } from "framer-motion";
import {
  Brain,
  BadgeCheck,
  AlertTriangle,
  Lightbulb,
} from "lucide-react";

import {
  Card,
  CardContent,
} from "@/components/ui/card";

const FeedbackCard = ({ feedback }) => {
  if (!feedback) return null;

  const sections = [
    {
      title: "Strengths",
      icon: BadgeCheck,
      color: "green",
      items: feedback.strengths || [],
    },
    {
      title: "Weaknesses",
      icon: AlertTriangle,
      color: "red",
      items: feedback.weaknesses || [],
    },
    {
      title: "Suggestions",
      icon: Lightbulb,
      color: "blue",
      items: feedback.suggestions || [],
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-xl hover:border-violet-500/40 hover:shadow-[0_0_40px_rgba(139,92,246,0.25)] transition-all duration-300">

        <CardContent className="p-8">

          {/* Header */}

          <div className="flex items-center gap-4 mb-8">

            <div className="rounded-2xl bg-violet-500/20 p-3">

              <Brain
                className="text-violet-400"
                size={28}
              />

            </div>

            <div>

              <h2 className="text-2xl font-bold text-white">
                AI Recruiter Feedback
              </h2>

              <p className="text-gray-400">
                Personalized insights generated by AI
              </p>

            </div>

          </div>

          {/* Sections */}

          <div className="grid gap-6 lg:grid-cols-3">

            {sections.map((section, index) => {
              const Icon = section.icon;

              const colors = {
                green: {
                  bg: "bg-green-500/10",
                  border: "border-green-500/20",
                  icon: "text-green-400",
                  title: "text-green-400",
                },
                red: {
                  bg: "bg-red-500/10",
                  border: "border-red-500/20",
                  icon: "text-red-400",
                  title: "text-red-400",
                },
                blue: {
                  bg: "bg-blue-500/10",
                  border: "border-blue-500/20",
                  icon: "text-blue-400",
                  title: "text-blue-400",
                },
              };

              const style = colors[section.color];

              return (
                <motion.div
                  key={index}
                  whileHover={{
                    y: -6,
                    scale: 1.02,
                  }}
                  className={`rounded-2xl border ${style.border} ${style.bg} p-5`}
                >
                  <div className="flex items-center gap-3 mb-5">

                    <Icon
                      className={style.icon}
                      size={22}
                    />

                    <h3
                      className={`font-semibold text-lg ${style.title}`}
                    >
                      {section.title}
                    </h3>

                  </div>

                  <ul className="space-y-3">

                    {section.items.length > 0 ? (
                      section.items.map((item, idx) => (
                        <li
                          key={idx}
                          className="flex items-start gap-3 text-gray-300"
                        >
                          <span className="mt-2 h-2 w-2 rounded-full bg-white/70" />

                          <span>{item}</span>

                        </li>
                      ))
                    ) : (
                      <p className="text-gray-500">
                        No data available
                      </p>
                    )}

                  </ul>

                </motion.div>
              );
            })}

          </div>

        </CardContent>

      </Card>
    </motion.div>
  );
};

export default FeedbackCard;