import { motion } from "framer-motion";
import { Brain, Sparkles, Clock3 } from "lucide-react";

import {
  Card,
  CardContent,
} from "@/components/ui/card";

import { ScrollArea } from "@/components/ui/scroll-area";

const SummaryCard = ({ summary }) => {
  if (!summary) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-xl transition-all duration-300 hover:border-indigo-500/40 hover:shadow-[0_0_40px_rgba(99,102,241,0.25)]">

        <CardContent className="p-8">

          {/* Header */}

          <div className="mb-8 flex items-center justify-between">

            <div className="flex items-center gap-4">

              <div className="rounded-2xl bg-indigo-500/20 p-3">

                <Brain
                  size={28}
                  className="text-indigo-400"
                />

              </div>

              <div>

                <h2 className="text-2xl font-bold text-white">
                  AI Resume Summary
                </h2>

                <p className="text-gray-400">
                  Generated using AI Resume Analysis
                </p>

              </div>

            </div>

            <Sparkles
              className="text-indigo-400"
              size={24}
            />

          </div>

          {/* Summary */}

          <div className="rounded-2xl border border-white/10 bg-black/20 p-6">

            <ScrollArea className="h-48 pr-4">

              <p className="leading-8 text-gray-300">
                {summary}
              </p>

            </ScrollArea>

          </div>

          {/* Footer */}

          <div className="mt-8 flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-5">

            <div>

              <p className="text-sm text-gray-400">
                Generated by
              </p>

              <h3 className="font-semibold text-white">
                ResumeAI
              </h3>

            </div>

            <div className="flex items-center gap-2 text-gray-400">

              <Clock3 size={18} />

              <span>~30 sec read</span>

            </div>

          </div>

        </CardContent>

      </Card>
    </motion.div>
  );
};

export default SummaryCard;